### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by jaanos** [jakamrak/APPR-2020-21#1]
Imam nekaj pripomb glede tvojega uvoza:

* Razpredelnica `gradbeni.stroski` ni v obliki *tidy data* - uporabi `pivot_longer`, da jo spraviš v tako obliko, torej namesto treh stolpcev za vsak tip stroška (ti podatki so med seboj primerljivi!) naj bo v razpredelnici en stolpec za tip stroška in en z vrednostjo. Načeloma tudi nočemo imeti izpeljanih podatkov - ime `SkupajStroski` nakazuje na to, čeprav očitno ne gre za vsote ali povprečja ostalih dveh. Če je torej to res neodvisen podatek, ga lahko pustiš, sicer ga pa odstrani.

* Izogibaj se znaka `%` v imenih stolpcev (kot tudi šumnikov in ostalih posebnih znakov). V grobem velja, da v imenih stolpcev ne uporabljaš ničesar, kar ne bi uporabil v imenih spremenljivk. Ker je `%` v R-ju posebej namenjen za uporabo v operatorjih (npr. `%%`, `%in%`, `%>%`), ga tako ni najbolje uporabljati za spremenljivke in stolpce.

* Pretvarjanje podatkov iz JSON v razpredelnico ne deluje (vsaj pri meni ne, pa tudi na Binderju), ker se pri pretvorbi v razpredelnico nizi pretvorijo v faktorje, zaradi česar pride do napake pri klicu funkcije `parse_number`. Da se temu izogneš, k `data.frame` dodaj še parameter `stringsAsFactors=FALSE`.

**Comment by jakamrak** [comment]
Pozdravljeni.
Najlepša hvala za komentar. Zdi se mi, da sem vse težave odpravil. Sem tudi zagnal binder in, če zaženem opcijo rStudio deluje, če pa sem zagnal Shiny sem dobil error, a sem ugotovil, da je to zato, ker sem izbrisal datoteko druzine.csv in uvoz za druzine zakomentiral ter se to potem ni skladalo s poročilom v markdownu.
Zdaj mislim, da vse deluje kot mora.
Lp, Jaka

**Comment by jaanos** [comment]
Uvoz in podatke iz vzorca lahko kar odstraniš, a poskrbi, da v poročilu ne kličeš programov, ki so ostali nespremenjeni (trenutno `vizualizacija.r` in `analiza.r`), ter ne izrisuješ grafov iz vzorca. Ustrezno kodo torej odstrani ali zakomentiraj, npr.
~~~R
```{r vizualizacija, results='hide'}
# source("vizualizacija/vizualizacija.r", encoding="UTF-8")
```
~~~
Svetujem sicer, da poročilo sproti dopolnjuješ - za začetek lahko dodaš opis teme in podatkov (kot za prvo predstavitev), kasneje pa boš dodal še izrisane grafe in njihove interpretacije.

**Comment by jaanos** [comment]
Še to: če meniš, da si razrešil probleme, opisane v tem issueju, ga lahko zapreš s klikom na *Close issue* (oziroma *Close with comment*, če ob tem še kaj napišeš).
