### ISSUE TITLE
Težava pri risanju grafov in vprašanje glede tabel

### ISSUE THREAD

**Issue by jakamrak** [jakamrak/APPR-2020-21#2]
Pozdravljeni!
Pri risanju grafov naletim na težavo, da se mi ne spremeni legenda tako kot želim. Prosil bi za pomoč pri tem. Dodajam kodo:
`graf_stroski <- gradbeni.stroski %>%
  ggplot(aes(x=Leto, y=Indeks, col=TipStroska)) +
  geom_line()+
  geom_point(size=2)+
  labs(title="Indeksi gradbenih stroškov")+
  #guides(fill=guide_legend("Tip stroška"))+
  xlab("Leto")+
  ylab("Indeks")+
  scale_x_continuous(name = "Leto", breaks = seq(2010,2019,1))+
  scale_y_continuous(name = "Indeks", breaks = seq(90,120,2))+
  theme(legend.title = element_text(color = "red", size = 10),
        legend.background = element_rect(fill = "darkgray"))+
  scale_fill_discrete(name = "Tip stroška", labels = 
                        c("Skupaj stroki", "Stroški dela", "Stroški materiala"))  #s tem sem zelel preimenovati elemente legende a ne dela`

Drugo vprašanje se nanaša na graf #3 (graf_infra.in.place), kjer bi želel skozi podatke potegniti premico, ki se jim prilagaja če je to možno a z `stat_smooth(method = "lm")` ne gre. 

Za konec me zanima še, ali je združevanje tabel iz več različnih prečiščenih v eno samo iz katere nato narišem graf vstrezno na način, kot sem ga ubral zaenkrat, in sicer tako, da to storim pred samim risanjem.

Hvala za odgovore in lep pozdrav.

**Comment by jaanos** [comment]
Pazi, da se funkcija za nastavitev legende ujema z imenom parametra pri `aes`, za katerega jo nastavljaš. V tvojem primeru nastavljaš legendo za `col` (kar je okrajšava za `color`), zato bo potrebno uporabiti funkcijo `scale_color_discrete`. Podobno je tudi pri nastavljanju legend s funkcijo `guides`.

Pri podajanju oznak se sicer spodobi povedati, katerim podatkom ustrezajo - tako se ni potrebno zanašati na vrstni red pojavitve. V tvojem primeru bi torej grafu lahko prištel sledeče:
```R
  scale_color_discrete(name="Tip stroška",
                       labels=c("SkupajStroski"="Skupaj stroški",
                                "StroskiDela"="Stroški dela",
                                "StroskiMateriala"="Stroški materiala"))
```

Pri zadnjem grafu premice ne nariše zato, ker barvaš točke in tako vzame vsako točko kot svojo skupino. Rešitev bi bila, da barvanje podaš posebej pri `geom_point`, da ne vpliva na `geom_smooth` (kar se običajno uporablja za risanje, čeprav očitno `stat_smooth` tudi deluje):
```R
graf_infra.in.place <- infra.in.place %>%
  ggplot(aes(x=Indeks, y=DelezVOdstotkih)) +
  geom_point(aes(color=StatisticnaRegija), size=2) +
  xlab("Indeks neto plač") +
  ylab("Delež stanovanj") +
  scale_y_continuous(name="Delež stanovanj [%]", breaks=seq(2, 10, 1)) +
  labs(title="Delež naseljenih stanovanj brez osnovne infrastrukture in indeks neto plač") +
  guides(color=guide_legend("Statistična regija")) +
  facet_grid(. ~ Leto) +
  geom_smooth(method="lm")
```
Sam bi sicer rekel, da so točke preveč razpršene, da bi se jih dalo pojasniti s takim linearnim modelom.

Drugače je združevanje podatkov iz različnih razpredelnic za potrebe vizualizacije povsem ustrezno.

Še to: opažam sledeče na začetku `vizualizacija.r`:
https://github.com/jakamrak/APPR-2020-21/blob/ac1d5dbcffc6a77e2cdf59e4a9ea3a46c150272c/vizualizacija/vizualizacija.r#L3-L4
Tega ne počni - ustrezna programa se namreč kličeta v poročilu že pred klicanjem vizualizacije, tako da se potem uvoz izvede dvakrat (podobno tudi v `uvoz.r` odstrani klicanje knjižnic). Pred začetkom dela enostavno poženi oba programa (lahko kar poženeš ustrezni vrstici v poročilu), da boš imel uvožene knjižnice in podatke.

Mimogrede, če želiš v issueju vključiti kodo v več vrsticah, lahko to narediš tako:
~~~markdown
```R
koda v R-ju
```
~~~
Pri tem oznaka `R` pomeni, da se bo koda ustrezno pobarvala kot koda v R-ju - po potrebi lahko namesto tega tam napišeš tudi ime katerega drugega programskega jezika, ali pa to izpustiš, da se koda ne obarva.

**Comment by jakamrak** [comment]
Super najlepša hvala. 
Za linearni model pri grafu 3 premica pride pricakovane oblike saj je pri nizji plači višji odstotek stanovanj brez os infrastrukture in obratno, tako da jo bom kar vključil.

Pozabil sem vprašati še glede tortnega diagrama (graf 1). Rad bi se znebil oznak na zunanju strani (0/100, 25...) a mi nikakor ne uspe. Poleg tega me zanima ali poznate kakšen boljši način za vključitev odstotkov posameznega dela diagrama v le-tega, saj bi si morda želel da je ta oznaka bolj ob zunanjem robu in bi se s tem izognil manjšem prekrivanju v primeru, ko je delež zelo majhen. Prilagam še kodo:
```R
##1
#PRIPRAVIM TABELO ZA RISANJE TORTNEGA DIAGRAMA

tortni <- gradb.dovoljenja.sept %>% 
  mutate(delezi = round(100*(gradb.dovoljenja.sept$SkupajObjekti) / 
                          sum(gradb.dovoljenja.sept$SkupajObjekti), digits = 2)) %>%
  arrange(desc(StatisticnaRegija)) %>%
  mutate(lab.ypos = cumsum(delezi) - 0.5*delezi)

#Tortni diagram gradbenih dovoljenj za september

graf_tortni <- ggplot(tortni) +
  aes(x="", y=delezi, fill=StatisticnaRegija) +
  geom_col(width=1) +
  coord_polar(theta="y") + xlab("") + ylab("") +
  geom_text(aes(y = lab.ypos, label = paste(delezi, "%", sep="")), color = "white", size = 2.5)+
  labs(title="Deleži izdanih gradbenih dovoljenj po regijah v mesecu septembru")+
  guides(fill=guide_legend("Statistična regija"))

```

**Comment by jaanos** [comment]
Če se hočeš znebiti oznak na osi, lahko grafu prišteješ `theme(axis.text=element_blank())`.

Boljšega načina za vključitev oznak na posamezno rezino ne poznam, tako da bo ta čisto v redu. Bi pa opozoril na to, da se številk ne zaokrožuje, dokler se bo z njimi še kaj računalo - zaokroževanje se opravi pri samem prikazu. Prav tako pri uporabi `mutate` in ostalih funkcij iz knjižnice `dplyr` (pa seveda tudi `aes` iz `ggplot2`) ni potrebno podajati imena razpredelnice, iz katere se črpa stolpec. Tako bi celotno gradnjo grafa lahko naredil tako:
```R
##1
#PRIPRAVIM TABELO ZA RISANJE TORTNEGA DIAGRAMA

tortni <- gradb.dovoljenja.sept %>%
  mutate(delezi=100*SkupajObjekti / sum(SkupajObjekti)) %>%
  arrange(desc(StatisticnaRegija)) %>%
  mutate(lab.ypos=cumsum(delezi) - 0.5*delezi)

#Tortni diagram gradbenih dovoljenj za september

graf_tortni <- ggplot(tortni) +
  aes(x="", y=delezi, fill=StatisticnaRegija) +
  geom_col(width=1) +
  coord_polar(theta="y") + xlab("") + ylab("") +
  geom_text(aes(y=lab.ypos, label=paste0(round(delezi, 2), "%")),
            x=1.3, color="white", size=2.5) +
  labs(title="Deleži izdanih gradbenih dovoljenj po regijah v mesecu septembru") +
  guides(fill=guide_legend("Statistična regija")) +
  theme(axis.text=element_blank())
```
Za postavitev besedila se tukaj uporabi parameter `x` pri `geom_text`. Glede na to, da se opravi pretvorba v polarne koordinate, bo večja vrednost `x` oznake premaknila bolj stran od sredine.

**Comment by jakamrak** [comment]
Najlepša hvala za pomoč in srečno novo leto 😁
