### ISSUE TITLE
Napaka z zemljevidom

### ISSUE THREAD

**Issue by MatejRojec** [jakamrak/APPR-2020-21#3]
Zemljevida se ne prevedeta pravilo na binderju. Probem je verjetno v tem , ko se uporabi funkcija right_join. Problem je verjetno v kodiranju znakov ko združiš tabeli skupaj z right_join:
```R
  geom_polygon(data = right_join(stanovanja.brez.os.infra.2018,Slovenija, by = "StatisticnaRegija")
```
Problem v podobnem stilu: https://github.com/tidyverse/dplyr/issues/1513

**Comment by jaanos** [comment]
Kolikor vidim, je tukaj težava s kodiranjem znakov, podanim pri `uvozi.zemljevid` - za zemljevide iz GADM je ustrezno kodiranje znakov **UTF-8**. 

Issue, ki ga navaja @MatejRojec, se nanaša na težavo pri združevanju stolpcev z imeni z različnimi kodiranji znakov, ki pa je očitno že razrešena. Vseeno pa služi kot opozorilo za morebitne težave, ki se lahko pojavijo pri uporabi šumnikov in drugih posebnih znakov v imenih stolpcev.

**Comment by jakamrak** [comment]
Hvala za opozorilo, nisem opazil ker mi je ob poganjanju datoteke`projekt.Rmd` na računalniku delovalo. Sem popravil kodiranje in sedaj se zemljevidi tudi na binderju v celoti izrišejo. Ali bi lahko preverili, če tudi vam deluje sedaj kot mora.
