### ISSUE TITLE
Barva imen y osi

### ISSUE THREAD

**Issue by jakamrak** [jakamrak/APPR-2020-21#4]
Zdravo. Zanima me, ali je možno nastaviti barvo vsake y-osi posebej v primeru, ko imam 2 in je vsaka za svoj "graf". Sepravi rad bi, da je ime iste barve kot obroba stolpcev oziroma kot linijski grafikon, da bi tako uporabnik vedel katera os je za posamezen graf. 

```R
##4
#PRIPRAVIM TABELO ZA RISANJE 

gradb.dela.in.arh.proj <- indeks.cen.arh.proj %>% 
  right_join(vrednost.gradb.del, by = "Leto") 

# diagram, ki kaže povezanost vrednosti opravljenih gradb del in cen arhitekturnega projektiranja
 
graf_gradb.dela.in.arh.proj <- gradb.dela.in.arh.proj %>% ggplot(aes(x=Leto)) +
  geom_line(aes(y=PovprecenIndeks), size = 1, color="red") +
  scale_x_continuous(breaks=seq(2010, 2018, 1)) +
  scale_y_continuous(breaks=seq(0, 150, 25), 
                     sec.axis = sec_axis(~.*17000, name = "Vrednost gradbenih del [1000EUR]"))+
  geom_col(aes(y = Vrednost_1000EUR/17000), size = 1, col="darkblue", fill="white", alpha=I(0)) +
  xlab("Leto") + ylab("Indeks cen arhitekturnega projektiranja") +
  labs(title="Primerjava indeksa cen arhitekturnega projektiranja in vrednosti 
       opravljenih gradbenih del") +
  theme(axis.title.y = element_text(color="red")) + #theme_clasic() ga povozi
  theme_classic()
#vprasi kako bi vsako y os dal svoje barve da je ena modra druga rdeča
```

**Comment by jaanos** [comment]
Če prav razumem, želiš spremeniti barvo oznak leve in desne osi y. To lahko storiš tako, da pri `theme` ustrezno nastaviš parametra `axis.title.y.left` in `axis.title.y.right`. Na podoben način lahko nastaviš tudi ostale elemente grafa (npr. črte osi, črtice oznak, pisavo oznak, itd. - poglej si pomoč funkcije `theme` za celoten seznam možnosti).

Mimogrede, če želiš uporabiti `theme_classic`, ga podaj pred `theme` - s slednjim potem povoziš le želene nastavitve.

Še to bi opomnil: takšen prikaz dveh lestvic na isti osi se načeloma odsvetuje, saj lahko zavaja (`ggplot2` ga ravno zato dolgo namenoma ni podpiral) - je pa res, da se da na tak način lepo primerjati dve vrednosti na različnih lestvicah. Je vsekakor dobrodošlo, da se lepo označi, katera os ustreza katerim podatkom, kot to poskušaš doseči z barvanjem.

**Comment by jakamrak** [comment]
Ja to sem mislil. Sem uredil. Mi priporočate kakšen drugačen prikaz v tem primeru, ker sem sam razmsišljal pa se mi v primerjalnem smislu zdi ta najbolj primeren. 

Morda bi vprašal še za grobo mnenje glede projekta ker sem sedaj nekako naredil vse kar sem si zamislil. Morda kakšne izboljšave ali kritike za kasneje.

**Comment by jaanos** [comment]
Ena možnost bi bila, da bi imel dva grafa, enega nad drugim - lahko bi uporabil `facet_grid` in poskrbel, da imata grafa skupno os x, a različni osi y. Ampak mislim, da je z barvanjem čisto v redu tudi na način, kot ga imaš.

Na hitro sem preletel tvoje poročilo, pa nimam pripomb na projekt. Boš pa seveda naslednji teden predstavil, pa morda takrat še kaj pripomnemo.

**Comment by jakamrak** [comment]
Dobro bom potem kar pustil tako, že ker sem se namatral poiskati to opcijo. 
Hvala za vso pomoč.
