### ISSUE TITLE
Napredna analiza

### ISSUE THREAD

**Issue by jakamrak** [jakamrak/APPR-2020-21#5]
Vseeno sem se lotil nekaj dodatnega gručenja pri napredni analizi a ob izrisu naletim na težavo. Šel sem po vajah vendar se mi vse izvede a ne izrise. Ko prevedem poročilo mi javi sledeči error : `Error: Object merge(Slovenija, skupine, by = "StatisticnaRegija") is neither from class sf, stars, Spatial, nor Raster.`

Dodajam še kodo saj se sam nisem uspel prebiti do rešitve:

```R

povprecna.dokoncana <- dokoncana.stanovanja.st.in.povrsina %>% 
  group_by(StatisticnaRegija) %>%
  summarise(PovprecnoSteviloZgrajenih = mean(StDokoncanihStanovanjNa1000Prebivalcev), 
            PovrpecnaVelikostZgrajena_m2=mean(PovprecnaPovrsina_m2))

povprecna.gradbena.dovoljenja <- gradbena.dovoljenja.letno %>% 
  group_by(StatisticnaRegija) %>%
  summarise(PovprecnoSteviloGradbenih = mean(SteviloStavb), 
            PovprecnaPovrsinaGradbena_m2 = mean(Povrsina_1000m2))

povprecen.indeks.plac <- indeks.neto.plac %>% 
  group_by(StatisticnaRegija) %>%
  summarise(PovprecenIndeksPlac = mean(Indeks))

povprecen.os.infra <- stanovanja.brez.os.infra %>% 
  group_by(StatisticnaRegija) %>%
  summarise(PovprecenDelezInfra = mean(DelezVOdstotkih))


povprecna.regije <- povprecna.dokoncana %>%
  left_join(povprecna.gradbena.dovoljenja, by="StatisticnaRegija") %>%
  left_join(povprecen.indeks.plac, by ="StatisticnaRegija") %>%
  left_join(povprecen.os.infra, by = "StatisticnaRegija")


data.norm <- povprecna.regije %>% .[c(2,3,4,5,6,7)] %>% scale()
rownames(data.norm) <- povprecna.regije$StatisticnaRegija

k <- kmeans(data.norm, 5, nstart=1000)

skupine <- data.frame(StatisticnaRegija=povprecna.regije$StatisticnaRegija,
                      skupina=factor(k$cluster))


graf_zemljevid.napredna.analiza <- tm_shape(merge(Slovenija, skupine, by = "StatisticnaRegija")) + 
  tm_polygons("skupina") 

```

Hvala za pomoč.

**Comment by jaanos** [comment]
Težava je v tem, da si zemljevid `Slovenija` pretvoril s `fortify` in je tako primeren za risanje z `ggplot` in ne `tmap`. Lahko torej tudi ta zemljevid izrišeš z `ggplot`, ali pa ohraniš zemljevid, ki ga vrne funkcija `uvozi.zemljevid`, za risanje s `tmap`, ter v drugo spremenljivko shraniš še zemljvid, dobljen s `fortify`, za risanje z `ggplot`.

**Comment by jakamrak** [comment]
Aha dobro. Sem potem kar z ggplotom narisel ker sem ga bol vešč. Hvala za pomoč. Ali je sedaj modeliranje vstrezno narejeno?

**Comment by jaanos** [comment]
Mislim, da bo v redu, ja.

**Comment by jakamrak** [comment]
Super. Hvala in lep pozdrav.
