### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by jakamrak** [jakamrak/APPR-2020-21#6]
Pozdravljeni. 
Sam mislim, da sem v projektu naredil vse kar sem si zamislil. Čeprav imam namen ustni zagovor opraviti nekoliko kasneje, bi vseeno rad malo prej vedel, če moram še kaj popraviti, ali se lahko samo zmenim za termin zagovora. Hvala za odgovor.

**Comment by jaanos** [comment]
Nimam pripomb, tako da bom dodal povezavo na repozitorij za zagovore, z @alenFMF pa se lahko domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

**Comment by jakamrak** [comment]
Super. Dogovorjeno.
